EIP-39 Monotonic box creation height
ergoplatform/eips pull request #80
Opened 2022-10-05 12:04 UTC by MrStahlfelge

2022-10-10 05:42 UTC, greenhat approved these changes

2022-10-10 05:42 UTC, greenhat commented on eip-0039.md
> +    OUTPUTS.allOf { output: Box => output.creationHeiht >= highestInputBoxHeight }
```suggestion
    OUTPUTS.allOf { output: Box => output.creationHeight >= highestInputBoxHeight }
```

2022-10-11 19:51 UTC, kushti requested changes
Please update index file also

2022-10-11 19:51 UTC, kushti commented on eip-0039.md
> +* Implemented: no
Now implemented

2022-10-11 19:51 UTC, kushti commented on eip-0039.md
> +* Forking: not needed for current draft
Soft-fork actually (new nodes will reject transactions breaking monotonic height rule, old nodes will accept both kinds of transactions).

2022-10-24 19:17 UTC, kushti approved these changes

2022-10-24 19:18 UTC, kushti commented
@MrStahlfelge approved, but please update EIPs index (readme.md) before merging

2022-10-24 19:43 UTC, merged