ErgoPay support multiple transactions and addresses
ergoplatform/eips pull request #82
Opened 2022-10-17 10:30 UTC by MrStahlfelge

First enhancement for ErgoPay: support signing multiple transactions at once
Second enhancement for ErgoPay: support using multiple addresses

2022-10-18 09:27 UTC, aslesarenko requested changes

2022-10-18 09:27 UTC, aslesarenko commented on eip-0020.md
> +  - reducedTx: ReducedTransaction (optional*)
I don't think we can just change the schema. If this change is really needed, then the spec should be versioned. So the current version is v1 and the change should be in version v2.

2022-10-18 09:27 UTC, aslesarenko commented on eip-0020.md
> +The `ErgoPaySigningRequest` must not contain `reducedTx` and `reducedTxList` fields.
```suggestion
The `ErgoPaySigningRequest` must not contain `reducedTx` and `reducedTxList` fields simultaneously.
```

2022-10-18 09:27 UTC, aslesarenko commented on eip-0020.md
> +In case `reducedTxList` array field and `replyToUrl` field is set, the data posted to this url is an
```suggestion
In case `reducedTxList` array field and `replyToUrl` field is set, the data POSTed to this url is an
```

Please also specify format of the POST message with the transaction id strings.

2022-10-18 09:31 UTC, MrStahlfelge commented on eip-0020.md
> +  - reducedTx: ReducedTransaction (optional*)
True, this is no change but a documentation fix. I should have mentioned it. The field was named wrong here (or in the code) and the real name used in the wild is `reducedTx`: https://github.com/ergoplatform/ergo-wallet-app/blob/23454d820026805e8eeabc7433a3f6831c1f2a1d/common-jvm/src/main/java/org/ergoplatform/transactions/ErgoPay.kt#L79

2022-10-18 18:31 UTC, aslesarenko approved these changes

2022-10-22 09:51 UTC, Luivatra commented
Would be very useful for ergopad to be able to redeem multiple vestings at once

2022-10-25 07:23 UTC, deadit approved these changes

2022-10-31 09:27 UTC, deadit approved these changes

2022-11-17 11:40 UTC, merged